SELECT DB_NAME() AS CurrentDatabase;

SELECT
    TABLE_SCHEMA,
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'stg'
  AND TABLE_NAME = 'CarListing';

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'stg'
  AND TABLE_NAME = 'CarListing'
ORDER BY ORDINAL_POSITION;

SELECT COUNT(*) AS CarListingRowCount
FROM stg.CarListing;
